# Analysez les données de systèmes éducatifs

## Exercice partie 1

### Etape 1 - Chargez les données dans votre Notebook

In [520]:
import numpy as np
import pandas as pd

# Permet d'afficher toutes les colonnes du dataframe
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [521]:
imported_countries = pd.read_csv('./data/EdStatsCountry.csv')
imported_country_series = pd.read_csv('./data/EdStatsCountry-Series.csv')
imported_data = pd.read_csv('./data/EdStatsData.csv')
imported_footnote = pd.read_csv('./data/EdStatsFootNote.csv')
imported_series = pd.read_csv('./data/EdStatsSeries.csv')

### Etape 2 - Collectez les informations basiques sur chaque jeu de données

In [522]:
# Fonction d'analyse des jeux de données
def analyze(file_name, data, categorial_columns):

    print(f"Le fichier {file_name} contient {data.shape[0]} lignes pour {data.shape[1]} colonnes. Il y à {data.duplicated().sum()} lignes dupliquée.")
    print("\n")

    for column in data.columns:
        print(column)
        nb_cell_empty = data[column].isnull().sum()
        print(f"Colonne {column} : {nb_cell_empty} cellules vides sur {data.shape[0]}, Soit {round((100 * nb_cell_empty) / data.shape[0])}% cellules vides.")

        # On utilise describe pour les colonnes numériques
        if data[column].dtype == 'int64' or data[column].dtype == 'float64':
            print(data[column].describe())

        # On affiche le nombre d'occurence par groupe pour les colonnes catégorielles
        if column in categorial_columns:
            print(data.groupby(column).size())

        print("\n")

#### **Analyse du fichier EdStatsCountry**

Chaque ligne du fichiers contient des informations sur un pays. Par exemple ci-dessus les informations du pays FRANCE

In [523]:
# Exemple d'une ligne du jeu de donnée
imported_countries.loc[imported_countries['Country Code'] == 'FRA']

   Country Code Short Name Table Name        Long Name 2-alpha code Currency Unit                                      Special Notes                 Region       Income Group WB-2 code                        National accounts base year  National accounts reference year                SNA price valuation Lending category Other groups                        System of National Accounts Alternative conversion factor PPP survey year             Balance of Payments Manual in use External debt Reporting status       System of trade    Government Accounting concept             IMF data dissemination standard                           Latest population census Latest household survey  Source of most recent Income and expenditure data Vital registration complete Latest agricultural census  Latest industrial data  Latest trade data Latest water withdrawal data  Unnamed: 31
71          FRA     France     France  French Republic           FR          Euro  A simple multiplier is used to convert the nat...  Europe & Central Asia  High income: OECD        FR  Original chained constant price data are resca...                            2005.0  Value added at basic prices (VAB)              NaN    Euro area  Country uses the 1993 System of National Accou...                           NaN         Rolling  IMF Balance of Payments Manual, 6th edition.                            NaN  Special trade system  Consolidated central government  Special Data Dissemination Standard (SDDS)  2006. Rolling census based on continuous sampl...                     NaN  Expenditure survey/budget survey (ES/BS), 1994/95                         Yes                       2010                  2009.0             2012.0                         2007          NaN

In [524]:
# Supression d'une colonne inconnue
imported_countries.drop('Unnamed: 31', axis=1, inplace=True)

categorial_cols = ['Region', 'Income Group', 'National accounts base year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'PPP survey year', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census']

# Analyse du fichier
analyze('EdStatsCountry', imported_countries, categorial_cols)

# On renomme cette colonne pour simplifier les jointures + tard
imported_countries.rename(columns={'Country Code' : 'CountryCode'}, inplace=True)

Le fichier EdStatsCountry contient 241 lignes pour 31 colonnes. Il y à 0 lignes dupliquée.


Country Code
Colonne Country Code : 0 cellules vides sur 241, Soit 0% cellules vides.


Short Name
Colonne Short Name : 0 cellules vides sur 241, Soit 0% cellules vides.


Table Name
Colonne Table Name : 0 cellules vides sur 241, Soit 0% cellules vides.


Long Name
Colonne Long Name : 0 cellules vides sur 241, Soit 0% cellules vides.


2-alpha code
Colonne 2-alpha code : 3 cellules vides sur 241, Soit 1% cellules vides.


Currency Unit
Colonne Currency Unit : 26 cellules vides sur 241, Soit 11% cellules vides.


Special Notes
Colonne Special Notes : 96 cellules vides sur 241, Soit 40% cellules vides.


Region
Colonne Region : 27 cellules vides sur 241, Soit 11% cellules vides.
Region
East Asia & Pacific           36
Europe & Central Asia         57
Latin America & Caribbean     41
Middle East & North Africa    21
North America                  3
South Asia                     8
Sub-Saharan Africa            48
dtype: int64


Income Group
Colonne Income Group : 27 cellules vides sur 241, Soit 11% cellules vides.
Income Group
High income: OECD       31
High income: nonOECD    44
Low income              34
Lower middle income     50
Upper middle income     55
dtype: int64


WB-2 code
Colonne WB-2 code : 1 cellules vides sur 241, Soit 0% cellules vides.


National accounts base year
Colonne National accounts base year : 36 cellules vides sur 241, Soit 15% cellules vides.
National accounts base year
1954                                                                                                                        1
1974                                                                                                                        1
1980                                                                                                                        1
1981/82. Reporting period switch from fiscal year to calendar year from 1996. Pre-1996 data converted to calendar year.     1
1982                                                                                                                        1
1984                                                                                                                        1
1985                                                                                                                        3
1986/87                                                                                                                     1
1987                                                                                                                        1
1988                                                                                                                        3
1990                                                                                                                       11
1990/91                                                                                                                     1
1991                                                                                                                        3
1991/92                                                                                                                     1
1994                                                                                                                        3
1995                                                                                                                        2
1995/96                                                                                                                     1
1996                                                                                                                        1
1997                                                                                                                        2
1997/98                                                                                                                     1
1998                                                                                                                        3
1999                                                                                                                        4
2000                                                                                                                       25
2000/01                                                                                                                     1
2001                                                                                                                        3
2001/02                                                                                                                     1
2002                                                                                                                        4
2002/03                                                                                                                     1
2003                                                                                                                        5
2004                                                                                                                        8
2004/05                                                                                                                     1
2005                                                                                                                       34
2005/06                                                                                                                     2
2005/2006                                                                                                                   1
2006                                                                                                                       19
2007                                                                                                                        9
2008                                                                                                                        3
2009                                                                                                                        3
2010                                                                                                                        6
2010/11                                                                                                                     1
2011                                                                                                                        2
2012                                                                                                                        1
Original chained constant price data are rescaled.                                                                         28
dtype: int64


National accounts reference year
Colonne National accounts reference year : 209 cellules vides sur 241, Soit 87% cellules vides.
count      32.00000
mean     2001.53125
std         5.24856
min      1987.00000
25%      1996.75000
50%      2002.00000
75%      2005.00000
max      2012.00000
Name: National accounts reference year, dtype: float64


SNA price valuation
Colonne SNA price valuation : 44 cellules vides sur 241, Soit 18% cellules vides.
SNA price valuation
Value added at basic prices (VAB)       163
Value added at producer prices (VAP)     34
dtype: int64


Lending category
Colonne Lending category : 97 cellules vides sur 241, Soit 40% cellules vides.
Lending category
Blend    18
IBRD     67
IDA      59
dtype: int64


Other groups
Colonne Other groups : 183 cellules vides sur 241, Soit 76% cellules vides.
Other groups
Euro area    18
HIPC         40
dtype: int64


System of National Accounts
Colonne System of National Accounts : 26 cellules vides sur 241, Soit 11% cellules vides.
System of National Accounts
Country uses the 1968 System of National Accounts methodology.     42
Country uses the 1993 System of National Accounts methodology.    165
Country uses the 2008 System of National Accounts methodology.      8
dtype: int64


Alternative conversion factor
Colonne Alternative conversion factor : 194 cellules vides sur 241, Soit 80% cellules vides.


PPP survey year
Colonne PPP survey year : 96 cellules vides sur 241, Soit 40% cellules vides.
PPP survey year
2005       98
2011       10
Rolling    37
dtype: int64


Balance of Payments Manual in use
Colonne Balance of Payments Manual in use : 60 cellules vides sur 241, Soit 25% cellules vides.


External debt Reporting status
Colonne External debt Reporting status : 117 cellules vides sur 241, Soit 49% cellules vides.
External debt Reporting status
Actual         107
Estimate        11
Preliminary      6
dtype: int64


System of trade
Colonne System of trade : 41 cellules vides sur 241, Soit 17% cellules vides.
System of trade
General trade system    106
Special trade system     94
dtype: int64


Government Accounting concept
Colonne Government Accounting concept : 80 cellules vides sur 241, Soit 33% cellules vides.
Government Accounting concept
Budgetary central government       66
Consolidated central government    95
dtype: int64


IMF data dissemination standard
Colonne IMF data dissemination standard : 60 cellules vides sur 241, Soit 25% cellules vides.
IMF data dissemination standard
General Data Dissemination System (GDDS)      110
Special Data Dissemination Standard (SDDS)     71
dtype: int64


Latest population census
Colonne Latest population census : 28 cellules vides sur 241, Soit 12% cellules vides.
Latest population census
1970                                                                                                                                                                               2
1979                                                                                                                                                                               1
1983                                                                                                                                                                               1
1984                                                                                                                                                                               2
1987                                                                                                                                                                               1
1989                                                                                                                                                                               1
1993                                                                                                                                                                               1
1996                                                                                                                                                                               1
1997                                                                                                                                                                               1
1998                                                                                                                                                                               2
2001                                                                                                                                                                               1
2002                                                                                                                                                                               5
2003                                                                                                                                                                               3
2004                                                                                                                                                                               7
2005                                                                                                                                                                               4
2006                                                                                                                                                                               8
2006. Rolling census based on continuous sample survey.                                                                                                                            1
2007                                                                                                                                                                               9
2008                                                                                                                                                                               9
2009                                                                                                                                                                              14
2010                                                                                                                                                                              49
2011                                                                                                                                                                              59
2011. Population figures compiled from administrative registers.                                                                                                                   3
2011. The population censuses for 1986 and 1996 were based on a one-in-seven sample of the population, while that for 2006 was based on a one-in-ten sample of the population.     1
2012                                                                                                                                                                              18
2013                                                                                                                                                                               8
Guernsey: 2009; Jersey: 2011.                                                                                                                                                      1
dtype: int64


Latest household survey
Colonne Latest household survey : 100 cellules vides sur 241, Soit 41% cellules vides.


Source of most recent Income and expenditure data
Colonne Source of most recent Income and expenditure data : 81 cellules vides sur 241, Soit 34% cellules vides.


Vital registration complete
Colonne Vital registration complete : 130 cellules vides sur 241, Soit 54% cellules vides.


Latest agricultural census
Colonne Latest agricultural census : 99 cellules vides sur 241, Soit 41% cellules vides.


Latest industrial data
Colonne Latest industrial data : 134 cellules vides sur 241, Soit 56% cellules vides.
count     107.000000
mean     2008.102804
std         2.616834
min      2000.000000
25%      2007.500000
50%      2009.000000
75%      2010.000000
max      2010.000000
Name: Latest industrial data, dtype: float64


Latest trade data
Colonne Latest trade data : 56 cellules vides sur 241, Soit 23% cellules vides.
count     185.000000
mean     2010.994595
std         2.569675
min      1995.000000
25%      2011.000000
50%      2012.000000
75%      2012.000000
max      2012.000000
Name: Latest trade data, dtype: float64


Latest water withdrawal data
Colonne Latest water withdrawal data : 62 cellules vides sur 241, Soit 26% cellules vides.

#### **Analyse du fichier EdStatsCountry-Series**

Chaque ligne du fichier contient des informations complémentaires sur les données.

C'est aussi une table de correspondance entre le fichier Pays et le fichier Stats

La clé CountryCode correspond a la clé Country Code dans le fichier EdStatsCountry, et la clé SeriesCode correspond à la clé Indicator Code dans le fichier EdStatsData

In [525]:
imported_country_series.loc[imported_country_series['CountryCode'] == 'FRA']

    CountryCode         SeriesCode                                        DESCRIPTION  Unnamed: 3
166         FRA        SP.POP.GROW  Data sources: Eurostat, United Nations World P...         NaN
167         FRA  SP.POP.TOTL.MA.ZS  Including the four French overseas departments...         NaN
168         FRA  SP.POP.TOTL.FE.ZS  Including the four French overseas departments...         NaN
169         FRA        SP.POP.TOTL  Data sources : Eurostat, United Nations World ...         NaN
170         FRA  SP.POP.0014.TO.ZS  Including the four French overseas departments...         NaN
171         FRA  SP.POP.1564.TO.ZS  Including the four French overseas departments...         NaN

In [526]:
# Supression d'une colonne
imported_country_series.drop('Unnamed: 3', axis=1, inplace=True)

analyze('EdStatsCountrySeries', imported_country_series, [])

Le fichier EdStatsCountrySeries contient 613 lignes pour 3 colonnes. Il y à 0 lignes dupliquée.


CountryCode
Colonne CountryCode : 0 cellules vides sur 613, Soit 0% cellules vides.


SeriesCode
Colonne SeriesCode : 0 cellules vides sur 613, Soit 0% cellules vides.


DESCRIPTION
Colonne DESCRIPTION : 0 cellules vides sur 613, Soit 0% cellules vides.

#### **Anayse du fichier EdStatsData**

Chaque ligne du fichier contient des statistiques par année

In [527]:
imported_data.head(2)

  Country Name Country Code                                     Indicator Name Indicator Code  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2020  2025  2030  2035  2040  2045  2050  2055  2060  2065  2070  2075  2080  2085  2090  2095  2100  Unnamed: 69
0   Arab World          ARB  Adjusted net enrolment rate, lower secondary, ...     UIS.NERA.2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN
1   Arab World          ARB  Adjusted net enrolment rate, lower secondary, ...   UIS.NERA.2.F   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN

In [528]:
imported_data.drop('Unnamed: 69', axis=1, inplace=True)

analyze('EdStatsData', imported_data, [])

# On renomme la colonne maintenant pour simplifier les jointures plus tard
imported_data.rename(columns={'Indicator Code' : 'SeriesCode', 'Country Code': 'CountryCode'}, inplace=True)

Le fichier EdStatsData contient 886930 lignes pour 69 colonnes. Il y à 0 lignes dupliquée.


Country Name
Colonne Country Name : 0 cellules vides sur 886930, Soit 0% cellules vides.


Country Code
Colonne Country Code : 0 cellules vides sur 886930, Soit 0% cellules vides.


Indicator Name
Colonne Indicator Name : 0 cellules vides sur 886930, Soit 0% cellules vides.


Indicator Code
Colonne Indicator Code : 0 cellules vides sur 886930, Soit 0% cellules vides.


1970
Colonne 1970 : 814642 cellules vides sur 886930, Soit 92% cellules vides.
count    7.228800e+04
mean     1.974772e+09
std      1.211687e+11
min     -1.435564e+00
25%      8.900000e-01
50%      6.317724e+00
75%      6.251250e+01
max      1.903929e+13
Name: 1970, dtype: float64


1971
Colonne 1971 : 851393 cellules vides sur 886930, Soit 96% cellules vides.
count    3.553700e+04
mean     4.253638e+09
std      1.804814e+11
min     -1.594625e+00
25%      8.853210e+00
50%      6.316240e+01
75%      5.655200e+04
max      1.986457e+13
Name: 1971, dtype: float64


1972
Colonne 1972 : 851311 cellules vides sur 886930, Soit 96% cellules vides.
count    3.561900e+04
mean     4.592365e+09
std      1.914083e+11
min     -3.056522e+00
25%      9.240920e+00
50%      6.655139e+01
75%      5.863650e+04
max      2.100916e+13
Name: 1972, dtype: float64


1973
Colonne 1973 : 851385 cellules vides sur 886930, Soit 96% cellules vides.
count    3.554500e+04
mean     5.105006e+09
std      2.059170e+11
min     -4.032582e+00
25%      9.595200e+00
50%      6.969595e+01
75%      6.202900e+04
max      2.238367e+13
Name: 1973, dtype: float64


1974
Colonne 1974 : 851200 cellules vides sur 886930, Soit 96% cellules vides.
count    3.573000e+04
mean     5.401493e+09
std      2.112150e+11
min     -4.213563e+00
25%      9.861595e+00
50%      7.087760e+01
75%      6.383675e+04
max      2.282991e+13
Name: 1974, dtype: float64


1975
Colonne 1975 : 799624 cellules vides sur 886930, Soit 90% cellules vides.
count    8.730600e+04
mean     2.314288e+09
std      1.375059e+11
min     -3.658569e+00
25%      1.400000e+00
50%      9.677420e+00
75%      7.854163e+01
max      2.300634e+13
Name: 1975, dtype: float64


1976
Colonne 1976 : 849447 cellules vides sur 886930, Soit 96% cellules vides.
count    3.748300e+04
mean     5.731808e+09
std      2.215546e+11
min     -2.950945e+00
25%      9.312615e+00
50%      7.101590e+01
75%      5.682800e+04
max      2.424128e+13
Name: 1976, dtype: float64


1977
Colonne 1977 : 849356 cellules vides sur 886930, Soit 96% cellules vides.
count    3.757400e+04
mean     6.124437e+09
std      2.325489e+11
min     -3.174870e+00
25%      9.519913e+00
50%      7.133326e+01
75%      5.739175e+04
max      2.521383e+13
Name: 1977, dtype: float64


1978
Colonne 1978 : 849354 cellules vides sur 886930, Soit 96% cellules vides.
count    3.757600e+04
mean     6.671489e+09
std      2.473986e+11
min     -3.558749e+00
25%      1.000000e+01
50%      7.290512e+01
75%      5.940425e+04
max      2.622101e+13
Name: 1978, dtype: float64


1979
Colonne 1979 : 850121 cellules vides sur 886930, Soit 96% cellules vides.
count    3.680900e+04
mean     7.436724e+09
std      2.660957e+11
min     -2.973612e+00
25%      1.000000e+01
50%      7.510173e+01
75%      6.411500e+04
max      2.730873e+13
Name: 1979, dtype: float64


1980
Colonne 1980 : 797808 cellules vides sur 886930, Soit 90% cellules vides.
count    8.912200e+04
mean     3.283898e+09
std      1.780774e+11
min     -1.404240e+00
25%      1.770000e+00
50%      1.107000e+01
75%      8.202760e+01
max      2.784319e+13
Name: 1980, dtype: float64


1981
Colonne 1981 : 848153 cellules vides sur 886930, Soit 96% cellules vides.
count    3.877700e+04
mean     7.664969e+09
std      2.744142e+11
min     -1.478345e+00
25%      9.468690e+00
50%      7.467213e+01
75%      6.310400e+04
max      2.837926e+13
Name: 1981, dtype: float64


1982
Colonne 1982 : 849419 cellules vides sur 886930, Soit 96% cellules vides.
count    3.751100e+04
mean     7.913722e+09
std      2.790549e+11
min     -2.358765e+00
25%      9.989330e+00
50%      7.710972e+01
75%      6.923300e+04
max      2.848067e+13
Name: 1982, dtype: float64


1983
Colonne 1983 : 848470 cellules vides sur 886930, Soit 96% cellules vides.
count    3.846000e+04
mean     7.856908e+09
std      2.823809e+11
min     -2.867273e+00
25%      9.581825e+00
50%      7.592528e+01
75%      6.304125e+04
max      2.916436e+13
Name: 1983, dtype: float64


1984
Colonne 1984 : 848324 cellules vides sur 886930, Soit 96% cellules vides.
count    3.860600e+04
mean     8.118002e+09
std      2.940635e+11
min     -2.800548e+00
25%      9.068048e+00
50%      7.533138e+01
75%      6.360700e+04
max      3.048521e+13
Name: 1984, dtype: float64


1985
Colonne 1985 : 796634 cellules vides sur 886930, Soit 90% cellules vides.
count    9.029600e+04
mean     3.622763e+09
std      2.002929e+11
min     -2.216315e+00
25%      2.150000e+00
50%      1.200000e+01
75%      8.338313e+01
max      3.166465e+13
Name: 1985, dtype: float64


1986
Colonne 1986 : 847558 cellules vides sur 886930, Soit 96% cellules vides.
count    3.937200e+04
mean     9.156550e+09
std      3.264675e+11
min     -1.556722e+00
25%      9.332923e+00
50%      7.409428e+01
75%      6.608525e+04
max      3.271284e+13
Name: 1986, dtype: float64


1987
Colonne 1987 : 848289 cellules vides sur 886930, Soit 96% cellules vides.
count    3.864100e+04
mean     1.014901e+10
std      3.535351e+11
min     -1.410886e+00
25%      9.595330e+00
50%      7.357014e+01
75%      7.001100e+04
max      3.388244e+13
Name: 1987, dtype: float64


1988
Colonne 1988 : 848378 cellules vides sur 886930, Soit 96% cellules vides.
count    3.855200e+04
mean     1.104709e+10
std      3.804257e+11
min     -1.425202e+00
25%      9.715503e+00
50%      7.354275e+01
75%      7.597875e+04
max      3.545738e+13
Name: 1988, dtype: float64


1989
Colonne 1989 : 849390 cellules vides sur 886930, Soit 96% cellules vides.
count    3.754000e+04
mean     1.195436e+10
std      4.014873e+11
min     -1.562425e+00
25%      9.679637e+00
50%      7.935322e+01
75%      8.558375e+04
max      3.678741e+13
Name: 1989, dtype: float64


1990
Colonne 1990 : 762525 cellules vides sur 886930, Soit 86% cellules vides.
count    1.244050e+05
mean     9.084424e+09
std      3.665667e+11
min     -1.803750e+00
25%      4.830000e+00
50%      5.048379e+01
75%      9.134300e+04
max      4.714344e+13
Name: 1990, dtype: float64


1991
Colonne 1991 : 812493 cellules vides sur 886930, Soit 92% cellules vides.
count    7.443700e+04
mean     1.571674e+10
std      4.881357e+11
min     -5.814339e+00
25%      5.134554e+01
50%      3.916000e+04
75%      4.383130e+05
max      4.781272e+13
Name: 1991, dtype: float64


1992
Colonne 1992 : 811387 cellules vides sur 886930, Soit 91% cellules vides.
count    7.554300e+04
mean     1.604668e+10
std      5.012055e+11
min     -5.089333e+00
25%      4.933854e+01
50%      3.477300e+04
75%      4.246125e+05
max      4.866446e+13
Name: 1992, dtype: float64


1993
Colonne 1993 : 811137 cellules vides sur 886930, Soit 91% cellules vides.
count    7.579300e+04
mean     1.643532e+10
std      5.121962e+11
min     -6.184857e+00
25%      4.944877e+01
50%      3.497100e+04
75%      4.316250e+05
max      4.959600e+13
Name: 1993, dtype: float64


1994
Colonne 1994 : 809468 cellules vides sur 886930, Soit 91% cellules vides.
count    7.746200e+04
mean     1.684022e+10
std      5.292982e+11
min     -4.792691e+00
25%      4.783283e+01
50%      3.182500e+04
75%      4.244605e+05
max      5.106581e+13
Name: 1994, dtype: float64


1995
Colonne 1995 : 755569 cellules vides sur 886930, Soit 85% cellules vides.
count    1.313610e+05
mean     1.052543e+10
std      4.285218e+11
min     -2.697722e+00
25%      5.200000e+00
50%      5.018663e+01
75%      7.954000e+04
max      5.275448e+13
Name: 1995, dtype: float64


1996
Colonne 1996 : 810123 cellules vides sur 886930, Soit 91% cellules vides.
count    7.680700e+04
mean     1.874630e+10
std      5.812586e+11
min     -3.820174e+00
25%      4.836486e+01
50%      3.262400e+04
75%      4.371055e+05
max      5.478031e+13
Name: 1996, dtype: float64


1997
Colonne 1997 : 813477 cellules vides sur 886930, Soit 92% cellules vides.
count    7.345300e+04
mean     2.027385e+10
std      6.142357e+11
min     -2.517245e+00
25%      5.510854e+01
50%      4.319600e+04
75%      4.909700e+05
max      5.695521e+13
Name: 1997, dtype: float64


1998
Colonne 1998 : 802016 cellules vides sur 886930, Soit 90% cellules vides.
count    8.491400e+04
mean     1.794678e+10
std      5.859148e+11
min     -6.086200e+04
25%      3.346871e+01
50%      1.521400e+04
75%      3.768212e+05
max      5.835137e+13
Name: 1998, dtype: float64


1999
Colonne 1999 : 768091 cellules vides sur 886930, Soit 87% cellules vides.
count    1.188390e+05
mean     1.331558e+10
std      5.153472e+11
min     -6.526000e+04
25%      1.749051e+01
50%      1.251000e+03
75%      1.867360e+05
max      6.040632e+13
Name: 1999, dtype: float64


2000
Colonne 2000 : 710254 cellules vides sur 886930, Soit 80% cellules vides.
count    1.766760e+05
mean     9.423384e+09
std      4.442374e+11
min     -6.759300e+04
25%      5.699035e+00
50%      5.078717e+01
75%      3.343950e+04
max      6.327293e+13
Name: 2000, dtype: float64


2001
Colonne 2001 : 763421 cellules vides sur 886930, Soit 86% cellules vides.
count    1.235090e+05
mean     1.384867e+10
std      5.449242e+11
min     -6.973700e+04
25%      1.599897e+01
50%      8.300000e+02
75%      1.746540e+05
max      6.477834e+13
Name: 2001, dtype: float64


2002
Colonne 2002 : 762725 cellules vides sur 886930, Soit 86% cellules vides.
count    1.242050e+05
mean     1.428299e+10
std      5.622886e+11
min     -9.214300e+04
25%      1.584246e+01
50%      9.460000e+02
75%      1.770990e+05
max      6.654753e+13
Name: 2002, dtype: float64


2003
Colonne 2003 : 756567 cellules vides sur 886930, Soit 85% cellules vides.
count    1.303630e+05
mean     1.449393e+10
std      5.803607e+11
min     -1.111860e+05
25%      1.550983e+01
50%      3.956150e+02
75%      1.474790e+05
max      6.906328e+13
Name: 2003, dtype: float64


2004
Colonne 2004 : 758116 cellules vides sur 886930, Soit 85% cellules vides.
count    1.288140e+05
mean     1.589729e+10
std      6.278337e+11
min     -1.262600e+05
25%      1.418687e+01
50%      3.350000e+02
75%      1.584082e+05
max      7.278829e+13
Name: 2004, dtype: float64


2005
Colonne 2005 : 702822 cellules vides sur 886930, Soit 79% cellules vides.
count    1.841080e+05
mean     1.188637e+10
std      5.576181e+11
min     -1.347240e+05
25%      5.720000e+00
50%      5.031512e+01
75%      2.993150e+04
max      7.624045e+13
Name: 2005, dtype: float64


2006
Colonne 2006 : 746618 cellules vides sur 886930, Soit 84% cellules vides.
count    1.403120e+05
mean     1.684674e+10
std      6.851484e+11
min     -3.708940e+05
25%      1.277624e+01
50%      9.981849e+01
75%      1.187198e+05
max      8.031840e+13
Name: 2006, dtype: float64


2007
Colonne 2007 : 749658 cellules vides sur 886930, Soit 85% cellules vides.
count    1.372720e+05
mean     1.872300e+10
std      7.465688e+11
min     -3.882170e+05
25%      1.268661e+01
50%      1.000000e+02
75%      1.343790e+05
max      8.469145e+13
Name: 2007, dtype: float64


2008
Colonne 2008 : 752543 cellules vides sur 886930, Soit 85% cellules vides.
count    1.343870e+05
mean     2.029794e+10
std      7.944132e+11
min     -4.088540e+05
25%      1.233467e+01
50%      1.000000e+02
75%      1.453855e+05
max      8.711022e+13
Name: 2008, dtype: float64


2009
Colonne 2009 : 744822 cellules vides sur 886930, Soit 84% cellules vides.
count    1.421080e+05
mean     1.894907e+10
std      7.623650e+11
min     -4.561240e+05
25%      1.181939e+01
50%      9.925039e+01
75%      1.180412e+05
max      8.677516e+13
Name: 2009, dtype: float64


2010
Colonne 2010 : 644488 cellules vides sur 886930, Soit 73% cellules vides.
count    2.424420e+05
mean     1.189592e+10
std      6.218710e+11
min     -4.969050e+05
25%      1.322703e+00
50%      2.046020e+01
75%      3.121000e+03
max      9.134676e+13
Name: 2010, dtype: float64


2011
Colonne 2011 : 740918 cellules vides sur 886930, Soit 84% cellules vides.
count    1.460120e+05
mean     2.117911e+10
std      8.555853e+11
min     -5.709940e+05
25%      1.216330e+01
50%      9.853510e+01
75%      1.065065e+05
max      9.506314e+13
Name: 2011, dtype: float64


2012
Colonne 2012 : 739666 cellules vides sur 886930, Soit 83% cellules vides.
count    1.472640e+05
mean     2.176323e+10
std      8.833955e+11
min     -6.049930e+05
25%      1.100000e+01
50%      9.759012e+01
75%      1.038168e+05
max      9.999473e+13
Name: 2012, dtype: float64


2013
Colonne 2013 : 749421 cellules vides sur 886930, Soit 84% cellules vides.
count    1.375090e+05
mean     2.425332e+10
std      9.513016e+11
min     -6.157480e+05
25%      1.306113e+01
50%      1.000000e+02
75%      1.426480e+05
max      1.054580e+14
Name: 2013, dtype: float64


2014
Colonne 2014 : 773141 cellules vides sur 886930, Soit 87% cellules vides.
count    1.137890e+05
mean     2.678449e+10
std      1.023180e+12
min     -8.900000e+01
25%      1.614639e+01
50%      1.000000e+02
75%      1.636440e+05
max      1.108060e+14
Name: 2014, dtype: float64


2015
Colonne 2015 : 755872 cellules vides sur 886930, Soit 85% cellules vides.
count    1.310580e+05
mean     2.353720e+10
std      9.732465e+11
min     -2.467847e+00
25%      4.100000e-01
50%      5.235000e+01
75%      6.153575e+04
max      1.156198e+14
Name: 2015, dtype: float64


2016
Colonne 2016 : 870470 cellules vides sur 886930, Soit 98% cellules vides.
count    1.646000e+04
mean     1.934411e+11
std      2.839188e+12
min     -1.797539e+00
25%      1.826761e+01
50%      6.264000e+03
75%      5.939590e+05
max      1.206030e+14
Name: 2016, dtype: float64


2017
Colonne 2017 : 886787 cellules vides sur 886930, Soit 100% cellules vides.
count    143.000000
mean       2.160839
std        0.810584
min        1.000000
25%        2.000000
50%        2.000000
75%        3.000000
max        4.000000
Name: 2017, dtype: float64


2020
Colonne 2020 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     5.780697e+02
std      1.475072e+04
min     -1.870000e+00
25%      6.000000e-02
50%      2.300000e-01
75%      6.660000e+00
max      1.599479e+06
Name: 2020, dtype: float64


2025
Colonne 2025 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     6.054774e+02
std      1.577305e+04
min     -2.000000e+00
25%      6.000000e-02
50%      2.300000e-01
75%      6.900000e+00
max      1.781898e+06
Name: 2025, dtype: float64


2030
Colonne 2030 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     6.315916e+02
std      1.678556e+04
min     -2.110000e+00
25%      6.000000e-02
50%      2.300000e-01
75%      7.062500e+00
max      1.967258e+06
Name: 2030, dtype: float64


2035
Colonne 2035 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     6.556516e+02
std      1.778666e+04
min     -2.150000e+00
25%      6.000000e-02
50%      2.300000e-01
75%      7.300000e+00
max      2.151416e+06
Name: 2035, dtype: float64


2040
Colonne 2040 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     6.751516e+02
std      1.874408e+04
min     -2.140000e+00
25%      5.000000e-02
50%      2.300000e-01
75%      7.400000e+00
max      2.330336e+06
Name: 2040, dtype: float64


2045
Colonne 2045 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     6.911287e+02
std      1.965409e+04
min     -2.090000e+00
25%      5.000000e-02
50%      2.300000e-01
75%      7.432500e+00
max      2.500439e+06
Name: 2045, dtype: float64


2050
Colonne 2050 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.040640e+02
std      2.052941e+04
min     -1.980000e+00
25%      4.000000e-02
50%      2.300000e-01
75%      7.500000e+00
max      2.662071e+06
Name: 2050, dtype: float64


2055
Colonne 2055 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.145788e+02
std      2.136851e+04
min     -1.830000e+00
25%      3.000000e-02
50%      2.300000e-01
75%      7.500000e+00
max      2.813670e+06
Name: 2055, dtype: float64


2060
Colonne 2060 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.224868e+02
std      2.215845e+04
min     -1.630000e+00
25%      3.000000e-02
50%      2.300000e-01
75%      7.505000e+00
max      2.951569e+06
Name: 2060, dtype: float64


2065
Colonne 2065 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.271290e+02
std      2.287990e+04
min     -1.440000e+00
25%      3.000000e-02
50%      2.300000e-01
75%      7.500000e+00
max      3.070879e+06
Name: 2065, dtype: float64


2070
Colonne 2070 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.283779e+02
std      2.352338e+04
min     -1.260000e+00
25%      2.000000e-02
50%      2.300000e-01
75%      7.300000e+00
max      3.169711e+06
Name: 2070, dtype: float64


2075
Colonne 2075 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.266484e+02
std      2.408149e+04
min     -1.090000e+00
25%      2.000000e-02
50%      2.300000e-01
75%      7.100000e+00
max      3.246239e+06
Name: 2075, dtype: float64


2080
Colonne 2080 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.228327e+02
std      2.455897e+04
min     -9.200000e-01
25%      1.000000e-02
50%      2.300000e-01
75%      6.722500e+00
max      3.301586e+06
Name: 2080, dtype: float64


2085
Colonne 2085 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.176899e+02
std      2.496587e+04
min     -7.800000e-01
25%      1.000000e-02
50%      2.300000e-01
75%      6.080000e+00
max      3.337871e+06
Name: 2085, dtype: float64


2090
Colonne 2090 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.113072e+02
std      2.530183e+04
min     -6.500000e-01
25%      1.000000e-02
50%      2.300000e-01
75%      5.462500e+00
max      3.354746e+06
Name: 2090, dtype: float64


2095
Colonne 2095 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     7.034274e+02
std      2.556069e+04
min     -5.500000e-01
25%      1.000000e-02
50%      2.300000e-01
75%      4.680000e+00
max      3.351887e+06
Name: 2095, dtype: float64


2100
Colonne 2100 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count    5.143600e+04
mean     6.940296e+02
std      2.574189e+04
min     -4.500000e-01
25%      1.000000e-02
50%      2.200000e-01
75%      4.032500e+00
max      3.330484e+06
Name: 2100, dtype: float64

In [529]:
imported_data.head(2)

  Country Name CountryCode                                     Indicator Name    SeriesCode  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2020  2025  2030  2035  2040  2045  2050  2055  2060  2065  2070  2075  2080  2085  2090  2095  2100
0   Arab World         ARB  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1   Arab World         ARB  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.F   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

#### **Analyse du fichier EdStatsFootNote**

Chaque ligne du fichier contient du détail pour certaines lignes de EdStatsData

La clé SeriesCode correspond à la clé Indicator Code dans le fichier EdStatsData

In [530]:
imported_footnote.head(2)

  CountryCode      SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.         NaN

In [531]:
imported_footnote.drop('Unnamed: 4', axis=1, inplace=True)

analyze('EdStatsFootNote', imported_footnote, [])

Le fichier EdStatsFootNote contient 643638 lignes pour 4 colonnes. Il y à 0 lignes dupliquée.


CountryCode
Colonne CountryCode : 0 cellules vides sur 643638, Soit 0% cellules vides.


SeriesCode
Colonne SeriesCode : 0 cellules vides sur 643638, Soit 0% cellules vides.


Year
Colonne Year : 0 cellules vides sur 643638, Soit 0% cellules vides.


DESCRIPTION
Colonne DESCRIPTION : 0 cellules vides sur 643638, Soit 0% cellules vides.

#### **Analyse du fichier EdStatsSeries**

Chaque ligne du fichier contient des explication concernant le type de donnée enregistré dans chaque cellule par année.

La clé Series Code correspond à la clé Indicator Code dans le fichier EdStatsData

In [532]:
imported_series.head(2)

           Series Code       Topic                                     Indicator Name                                   Short definition                                    Long definition  Unit of measure Periodicity Base Period Other notes Aggregation method Limitations and exceptions  Notes from original source General comments                                             Source Statistical concept and methodology Development relevance Related source links  Other web links  Related indicators  License Type  Unnamed: 20
0  BAR.NOED.1519.FE.ZS  Attainment  Barro-Lee: Percentage of female population age...  Percentage of female population age 15-19 with...  Percentage of female population age 15-19 with...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN          NaN
1     BAR.NOED.1519.ZS  Attainment  Barro-Lee: Percentage of population age 15-19 ...  Percentage of population age 15-19 with no edu...  Percentage of population age 15-19 with no edu...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN          NaN

In [533]:
# Supression d'une colonne inconnue
imported_series.drop('Unnamed: 20', axis=1, inplace=True)

analyze('EdStatsSeries', imported_series, [])

imported_series.rename(columns={'Series Code' : 'SeriesCode'}, inplace=True)

Le fichier EdStatsSeries contient 3665 lignes pour 20 colonnes. Il y à 0 lignes dupliquée.


Series Code
Colonne Series Code : 0 cellules vides sur 3665, Soit 0% cellules vides.


Topic
Colonne Topic : 0 cellules vides sur 3665, Soit 0% cellules vides.


Indicator Name
Colonne Indicator Name : 0 cellules vides sur 3665, Soit 0% cellules vides.


Short definition
Colonne Short definition : 1509 cellules vides sur 3665, Soit 41% cellules vides.


Long definition
Colonne Long definition : 0 cellules vides sur 3665, Soit 0% cellules vides.


Unit of measure
Colonne Unit of measure : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Unit of measure, dtype: float64


Periodicity
Colonne Periodicity : 3566 cellules vides sur 3665, Soit 97% cellules vides.


Base Period
Colonne Base Period : 3351 cellules vides sur 3665, Soit 91% cellules vides.


Other notes
Colonne Other notes : 3113 cellules vides sur 3665, Soit 85% cellules vides.


Aggregation method
Colonne Aggregation method : 3618 cellules vides sur 3665, Soit 99% cellules vides.


Limitations and exceptions
Colonne Limitations and exceptions : 3651 cellules vides sur 3665, Soit 100% cellules vides.


Notes from original source
Colonne Notes from original source : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Notes from original source, dtype: float64


General comments
Colonne General comments : 3651 cellules vides sur 3665, Soit 100% cellules vides.


Source
Colonne Source : 0 cellules vides sur 3665, Soit 0% cellules vides.


Statistical concept and methodology
Colonne Statistical concept and methodology : 3642 cellules vides sur 3665, Soit 99% cellules vides.


Development relevance
Colonne Development relevance : 3662 cellules vides sur 3665, Soit 100% cellules vides.


Related source links
Colonne Related source links : 3450 cellules vides sur 3665, Soit 94% cellules vides.


Other web links
Colonne Other web links : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Other web links, dtype: float64


Related indicators
Colonne Related indicators : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: Related indicators, dtype: float64


License Type
Colonne License Type : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: License Type, dtype: float64

### Etape 3 - Réalisez votre premier nettoyage

#### Supression des faux pays

In [534]:
countries_cleaned = imported_countries[ ~ imported_countries['Region'].isnull()]

Ma méthode naïve a été de téléchargé la liste des country code disponible sur kaggle ici : https://www.kaggle.com/datasets/wbdill/country-codes-iso-3166?resource=download

Et j'ai mergé le fichier EdStatsCountry en inner pour ne garder que les codes des pays qui sont présent dans les deux fichiers.

In [535]:
import pandas as pd
countries_iso3166b = pd.read_csv('./data/countries_iso3166b.csv', sep=',', na_values=[''], quotechar='"', encoding='ISO-8859-1')
filtered_countries = imported_countries.merge(countries_iso3166b, left_on='CountryCode', right_on='iso3', how='inner')
filtered_countries.head()

  CountryCode   Short Name   Table Name                     Long Name 2-alpha code   Currency Unit                                      Special Notes                     Region          Income Group WB-2 code                        National accounts base year  National accounts reference year                   SNA price valuation Lending category Other groups                        System of National Accounts Alternative conversion factor PPP survey year             Balance of Payments Manual in use External debt Reporting status       System of trade    Government Accounting concept           IMF data dissemination standard                           Latest population census                            Latest household survey  Source of most recent Income and expenditure data Vital registration complete Latest agricultural census  Latest industrial data  Latest trade data Latest water withdrawal data iso2 iso3  iso_num      country country_common
0         ABW        Aruba        Aruba                         Aruba           AW   Aruban florin  SNA data for 2000-2011 are updated from offici...  Latin America & Caribbean  High income: nonOECD        AW                                               2000                               NaN     Value added at basic prices (VAB)              NaN          NaN  Country uses the 1993 System of National Accou...                           NaN             NaN  IMF Balance of Payments Manual, 6th edition.                            NaN  Special trade system                              NaN                                       NaN                                               2010                                                NaN                                                NaN                         Yes                        NaN                     NaN             2012.0                          NaN   AW  ABW      533        Aruba          Aruba
1         AFG  Afghanistan  Afghanistan  Islamic State of Afghanistan           AF  Afghan afghani  Fiscal year end: March 20; reporting period fo...                 South Asia            Low income        AF                                            2002/03                               NaN     Value added at basic prices (VAB)              IDA         HIPC  Country uses the 1993 System of National Accou...                           NaN             NaN                                           NaN                         Actual  General trade system  Consolidated central government  General Data Dissemination System (GDDS)                                               1979  Multiple Indicator Cluster Survey (MICS), 2010/11            Integrated household survey (IHS), 2008                         NaN                    2013/14                     NaN             2012.0                         2000   AF  AFG        4  Afghanistan    Afghanistan
2         AGO       Angola       Angola   People's Republic of Angola           AO  Angolan kwanza  April 2013 database update: Based on IMF data,...         Sub-Saharan Africa   Upper middle income        AO                                               2002                               NaN  Value added at producer prices (VAP)             IBRD          NaN  Country uses the 1993 System of National Accou...                       1991–96            2005  IMF Balance of Payments Manual, 6th edition.                         Actual  Special trade system     Budgetary central government  General Data Dissemination System (GDDS)                                               1970               Malaria Indicator Survey (MIS), 2011            Integrated household survey (IHS), 2008                         NaN                       2015                     NaN                NaN                         2005   AO  AGO       24       Angola         Angola
3         ALB      Albania      Albania           Republic of Albania           AL    Albanian lek                                                NaN      Europe & Central Asia   Upper middle income        AL  Original chained constant price data are resca...                            1996.0     Value added at basic prices (VAB)             IBRD          NaN  Country uses the 1993 System of National Accou...                           NaN         Rolling  IMF Balance of Payments Manual, 6th edition.                         Actual  General trade system     Budgetary central government  General Data Dissemination System (GDDS)                                               2011       Demographic and Health Survey (DHS), 2008/09  Living Standards Measurement Study Survey (LSM...                         Yes                       2012                  2010.0             2012.0                         2006   AL  ALB        8      Albania        Albania
4         AND      Andorra      Andorra       Principality of Andorra           AD            Euro                                                NaN      Europe & Central Asia  High income: nonOECD        AD                                               1990                               NaN                                   NaN              NaN          NaN  Country uses the 1968 System of National Accou...                           NaN             NaN                                           NaN                            NaN  Special trade system                              NaN                                       NaN  2011. Population figures compiled from adminis...                                                NaN                                                NaN                         Yes                        NaN                     NaN             2006.0                          NaN   AD  AND       20      Andorra        Andorra

Mais j'ai remarqué après ques les faux pays sont ceux du jeu de donnée qui n'ont pas de région associée. On peut filtrer les pays de cette manière.

In [536]:
countries_cleaned = imported_countries[ ~ imported_countries['Region'].isnull()]

#### Supression des faux pays dans les autres df

##### Méthode 1

En stockant les faux pays dans une liste qui sera utilisée pour le filtrage des différents dataframes.

In [537]:
# On enregistre les pays a supprimer
print(f'Nombre de pays total : {imported_countries.shape[0]}')
countries_to_remove = imported_countries[imported_countries['Region'].isnull()]
print(f'Country a supprimer : {countries_to_remove.shape[0]}')
print(f'Country restant : {imported_countries.shape[0] - countries_to_remove.shape[0]}')

# On supprime les country series dont le countryCode est dans la liste des pays à supprimer
print(f'Country series avant : {imported_country_series.shape}')
method_one_country_series_filtered = imported_country_series[ ~ imported_country_series['CountryCode'].isin(countries_to_remove['CountryCode'])]
print(f'Country series après : {method_one_country_series_filtered.shape}')

# On supprime les stats data dont le countryCode est dans la liste des pays à supprimer
print(f'Stats data avant : {imported_data.shape}')
method_one_stats_filtered = imported_data[ ~ imported_data['CountryCode'].isin(countries_to_remove['CountryCode'])]
print(f'Stats data après : {method_one_stats_filtered.shape}')

# On supprime les footnote dont le countryCode est dans la liste des pays à supprimer
print(f'Footnote avant : {imported_footnote.shape}')
method_one_footnote_filtered = imported_footnote[ ~ imported_footnote['CountryCode'].isin(countries_to_remove['CountryCode'])]
print(f'Footnote après : {method_one_footnote_filtered.shape}')

Nombre de pays total : 241
Country a supprimer : 27
Country restant : 214
Country series avant : (613, 3)
Country series après : (611, 3)
Stats data avant : (886930, 69)
Stats data après : (787975, 69)
Footnote avant : (643638, 4)
Footnote après : (516743, 4)

##### Méthode 2

En utilisant un inner join entre les pays du dataframe Country nettoyé, et les autres dataframes.

In [538]:
# On joint le df country au df country_series sur la colonne CountryCode en inner pour s'assurer d'avoir une jointure sans faux pays
print(f'Country series avant : {imported_country_series.shape}')
method_two_country_series_fitered = imported_country_series.merge(countries_cleaned, how='inner')
print(f'Country series avant : {method_two_country_series_fitered.shape}')

# On joint a le df method_two_country_series_fitered au df stats en inner pour s'assurer de ne garder que les stats qui ont un SeriesCode qui est présent dans les SeriesCode de notre df method_two_country_series_fitered
print(f'Stats data avant : {imported_data.shape}')
method_two_stats_filtered = imported_data.merge(method_two_country_series_fitered, how='inner')
print(f'Stats data après : {method_one_stats_filtered.shape}')

# On joint
print(f'Footnote avant : {imported_footnote.shape}')
method_two_footnote_filtered = imported_footnote.merge(method_two_country_series_fitered, how='inner')
print(f'Footnote après : {method_one_footnote_filtered.shape}')

Country series avant : (613, 3)
Country series avant : (611, 33)
Stats data avant : (886930, 69)
Stats data après : (787975, 69)
Footnote avant : (643638, 4)
Footnote après : (516743, 4)

## Exercice partie 2

### Etape 1 - Réduisez le périmètre en utilisant une approche métier

In [539]:
# Parmi les jeux de données centrés sur les indicateurs, identifiez la colonne qui décrit la catégorie métier à laquelle appartient chaque indicateur.
imported_series['Topic'].value_counts()

Topic
Learning Outcomes                                                                               1046
Attainment                                                                                       733
Education Equality                                                                               426
Secondary                                                                                        256
Primary                                                                                          248
Population                                                                                       213
Tertiary                                                                                         158
Teachers                                                                                         137
Expenditures                                                                                      93
Engaging the Private Sector (SABER)                                                               51
Literacy                                                                                          32
School Autonomy and Accountability (SABER)                                                        29
Teachers (SABER)                                                                                  29
Early Childhood Education                                                                         24
Education Management Information Systems (SABER)                                                  23
Post-Secondary/Non-Tertiary                                                                       19
School Finance (SABER)                                                                            18
Tertiary Education (SABER)                                                                        17
Student Assessment (SABER)                                                                        15
Pre-Primary                                                                                       14
Health: Population: Structure                                                                     13
Early Child Development (SABER)                                                                   12
Workforce Development (SABER)                                                                     12
Social Protection & Labor: Labor force structure                                                  11
School Health and School Feeding (SABER)                                                           9
Economic Policy & Debt: Purchasing power parity                                                    6
Economic Policy & Debt: National accounts: US$ at current prices: Aggregate indicators             3
Laber                                                                                              3
Social Protection & Labor: Unemployment                                                            3
Infrastructure: Communications                                                                     2
Economic Policy & Debt: National accounts: US$ at constant 2010 prices: Aggregate indicators       2
Background                                                                                         2
EMIS                                                                                               2
Economic Policy & Debt: National accounts: Atlas GNI & GNI per capita                              1
Health: Risk factors                                                                               1
Health: Mortality                                                                                  1
Health: Population: Dynamics                                                                       1
Name: count, dtype: int64

Catégories utiles :
- Learning Outcomes (Résultats d'apprentissage)
- Attainment (Niveau d'instruction (ou Niveau d'études atteint)
- Secondary (Secondaire)
- Tertiary (Supérieur)
- Teachers (Enseignants)
- Literacy (Alphabétisation)
- Infrastructure: Communications
- Population (population)

In [595]:
# Gardez les catégories qui font sens par rapport à la demande de Mark et l’objectif du projet et supprimez les autres.
# significant_topics = ['']
significant_topics = ['Learning Outcomes', 'Attainment', 'Secondary', 'Tertiary', 'Teachers', 'Literacy', 'Infrastructure', 'Population']
significative_series = imported_series[imported_series['Topic'].isin(significant_topics)]

# Calculez le nombre d’indicateurs restants.
print(f'Indicateurs avant filtrage : {imported_series.shape}')
print(f'Indicateurs après filtrage : {significative_series.shape}')

significative_series['Topic'].value_counts()

Indicateurs avant filtrage : (3665, 20)
Indicateurs après filtrage : (2575, 20)

Topic
Learning Outcomes    1046
Attainment            733
Secondary             256
Population            213
Tertiary              158
Teachers              137
Literacy               32
Name: count, dtype: int64

In [596]:
significative_series.head()

            SeriesCode       Topic                                     Indicator Name                                   Short definition                                    Long definition  Unit of measure Periodicity Base Period Other notes Aggregation method Limitations and exceptions  Notes from original source General comments                                             Source Statistical concept and methodology Development relevance Related source links  Other web links  Related indicators  License Type
0  BAR.NOED.1519.FE.ZS  Attainment  Barro-Lee: Percentage of female population age...  Percentage of female population age 15-19 with...  Percentage of female population age 15-19 with...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN
1     BAR.NOED.1519.ZS  Attainment  Barro-Lee: Percentage of population age 15-19 ...  Percentage of population age 15-19 with no edu...  Percentage of population age 15-19 with no edu...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN
2  BAR.NOED.15UP.FE.ZS  Attainment  Barro-Lee: Percentage of female population age...  Percentage of female population age 15+ with n...  Percentage of female population age 15+ with n...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN
3     BAR.NOED.15UP.ZS  Attainment  Barro-Lee: Percentage of population age 15+ wi...  Percentage of population age 15+ with no educa...  Percentage of population age 15+ with no educa...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN
4  BAR.NOED.2024.FE.ZS  Attainment  Barro-Lee: Percentage of female population age...  Percentage of female population age 20-24 with...  Percentage of female population age 20-24 with...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN

In [597]:
# Filtrez l’ensemble des jeux de données pour ne garder que les indicateurs sélectionnés.

print(f'Country series avant : {method_one_country_series_filtered.shape}')
country_series_filtered = method_one_country_series_filtered[method_one_country_series_filtered['SeriesCode'].isin(significative_series['SeriesCode'])]
print(f'Country series après : {country_series_filtered.shape}')

print(f'Stats data avant : {method_one_stats_filtered.shape}')
stats_filtered = method_one_stats_filtered[method_one_stats_filtered['SeriesCode'].isin(significative_series['SeriesCode'])]
print(f'Stats data après : {stats_filtered.shape}')

print(f'Footnote avant : {method_one_footnote_filtered.shape}')
footnote_filtered = method_one_footnote_filtered[method_one_footnote_filtered['SeriesCode'].isin(significative_series['SeriesCode'])]
print(f'Footnote après : {footnote_filtered.shape}')

Country series avant : (611, 3)
Country series après : (0, 3)
Stats data avant : (787975, 69)
Stats data après : (547175, 69)
Footnote avant : (516743, 4)
Footnote après : (278882, 4)

Dans le fichier Data, interprétez les colonnes représentant les années.

Pourquoi avons-nous des valeurs d’indicateur pour des années futures ?
A but de projections futures

In [598]:
imported_data.loc[~imported_data['2100'].isnull()]

       Country Name CountryCode                                     Indicator Name        SeriesCode  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009     2010  2011  2012  2013  2014     2015  2016  2017     2020     2025     2030     2035     2040     2045     2050     2055     2060     2065     2070     2075     2080     2085     2090     2095     2100
91309         World         WLD  Wittgenstein Projection: Mean years of schooli...   PRJ.MYS.0T19.FE   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     2.00   NaN   NaN   NaN   NaN     2.00   NaN   NaN     2.00     2.10     2.20     2.30     2.30     2.30     2.40     2.50     2.50     2.50     2.60     2.60     2.60     2.70     2.70     2.70     2.70
91310         World         WLD  Wittgenstein Projection: Mean years of schooli...   PRJ.MYS.0T19.MA   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     2.00   NaN   NaN   NaN   NaN     2.00   NaN   NaN     2.00     2.10     2.20     2.20     2.30     2.30     2.40     2.40     2.50     2.50     2.60     2.60     2.60     2.70     2.70     2.70     2.70
91311         World         WLD  Wittgenstein Projection: Mean years of schooli...   PRJ.MYS.0T19.MF   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     2.00   NaN   NaN   NaN   NaN     2.00   NaN   NaN     2.00     2.10     2.20     2.30     2.30     2.30     2.40     2.40     2.50     2.50     2.60     2.60     2.60     2.70     2.70     2.70     2.70
91312         World         WLD  Wittgenstein Projection: Mean years of schooli...   PRJ.MYS.15UP.FE   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     7.60   NaN   NaN   NaN   NaN     8.00   NaN   NaN     8.30     8.70     9.00     9.30     9.70    10.00    10.30    10.60    10.80    11.10    11.40    11.60    11.90    12.10    12.30    12.50    12.70
91313         World         WLD  Wittgenstein Projection: Mean Years of Schooli...  PRJ.MYS.15UP.GPI   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN     0.89   NaN   NaN   NaN   NaN     0.79   NaN   NaN     0.70     0.61     0.53     0.45     0.38     0.33     0.28     0.24     0.21     0.17     0.15     0.12     0.11     0.10     0.09     0.08     0.08
...             ...         ...                                                ...               ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...      ...   ...   ...   ...   ...      ...   ...   ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...
886917     Zimbabwe         ZWE  Wittgenstein Projection: Population in thousan...  PRJ.POP.ALL.1.MA   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   799.57   NaN   NaN   NaN   NaN   721.56   NaN   NaN   660.67   605.74   538.90   471.82   407.10   347.67   297.53   253.28   212.14   179.40   150.11   126.43   106.82    91.70    78.21    67.56    59.06
886918     Zimbabwe         ZWE  Wittgenstein Projection: Population in thousan...  PRJ.POP.ALL.1.MF   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  1614.84   NaN   NaN   NaN   NaN  1474.43   NaN   NaN  1360.77  1253.78  1124.63   995.32   870.21   755.65   659.02   574.00   494.23   420.47   352.09   294.10   244.68   205.47   171.39   144.86   124.17
886919     Zimbabwe         ZWE  Wittgenstein Projection: Population in thousan...  PRJ.POP.ALL.3.FE   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  1401.82   NaN   NaN   NaN   NaN  1722.96   NaN   NaN  2052.78  2365.85  2655.48  2902.52  3104.10  3253.97  3361.11  3434.09  3469.66  3493.32  3491.72  3468.64  3429.54  3378.61  3317.67  3248.91  3175.64
886920     Zimbabwe         ZWE  Wittgenstein Projection: Population in thousan...  PRJ.POP.ALL.3.MA   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  1608.65   NaN   NaN   NaN   NaN  1873.55   NaN   NaN  2154.54  2413.51  2641.34  2826.96  2970.06  3060.45  3108.34  3124.32  3106.84  3078.78  3041.50  3000.74  2961.23  2924.73  2889.02  2851.65  2813.31
886921     Zimbabwe         ZWE  Wittgenstein Projection: Population in thousan...  PRJ.POP.ALL.3.MF   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  3010.47   NaN   NaN   NaN   NaN  3596.51   NaN   NaN  4207.33  4779.36  5296.82  5729.49  6074.16  6314.43  6469.45  6558.41  6576.50  6572.10  6533.22  6469.39  6390.77  6303.34  6206.69  6100.56  5988.95

[51436 rows x 69 columns]

In [599]:
# Sur la base de votre compréhension de la problématique métier, filtrez les années en conséquence.
# Je supprime les colonnes des années au delas de 2016

import numpy as np

# On retire les année après 2016 qui sont des projection
columns_to_drop = np.arange(2020,2105,5)
columns_to_drop = [str(col) for col in columns_to_drop]
print(f'Shape avant : {stats_filtered.shape}')
stats_filtered.drop(columns=columns_to_drop, inplace=True)
print(f'Shape après : {stats_filtered.shape}')

# On retire les année avant 2000 qui sont un peu vieille
columns_to_drop = np.arange(1970,2000,1)
columns_to_drop = [str(col) for col in columns_to_drop]
print(f'Shape avant : {stats_filtered.shape}')
stats_filtered.drop(columns=columns_to_drop, inplace=True)
print(f'Shape après : {stats_filtered.shape}')

stats_filtered.head(2)

Shape avant : (547175, 69)
Shape après : (547175, 52)
Shape avant : (547175, 52)
Shape après : (547175, 22)

      Country Name CountryCode                                     Indicator Name    SeriesCode  2000  2001  2002  2003  2004  2005  2006      2007  2008  2009  2010  2011  2012       2013       2014  2015  2016  2017
91625  Afghanistan         AFG  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2   NaN   NaN   NaN   NaN   NaN   NaN   NaN  28.05987   NaN   NaN   NaN   NaN   NaN  47.436790  50.627232   NaN   NaN   NaN
91626  Afghanistan         AFG  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.F   NaN   NaN   NaN   NaN   NaN   NaN   NaN  15.22310   NaN   NaN   NaN   NaN   NaN  34.073261  37.641541   NaN   NaN   NaN

### Etape 2 - Réduisez le périmètre en utilisant une approche data

In [600]:
# Pour chaque année, calculez la proportion d’indicateurs avec des valeurs renseignées (c’est-à-dire, non manquantes).

years = np.arange(2000,2018, 1)
cols = [str(col) for col in years]

stats_by_year = stats_filtered[cols]
stats_by_year.notnull().mean()

2000    0.235676
2001    0.139299
2002    0.139460
2003    0.150117
2004    0.143276
2005    0.238068
2006    0.156007
2007    0.153145
2008    0.147130
2009    0.160660
2010    0.338356
2011    0.162316
2012    0.166400
2013    0.152872
2014    0.126285
2015    0.204437
2016    0.012075
2017    0.000000
dtype: float64

In [601]:
# Pour chaque indicateur, calculez la proportion d’années avec des valeurs renseignées.

years = np.arange(2000,2018, 1)
cols = [str(col) for col in years]

stats_by_year = stats_filtered[cols]

stats_filtered['percentage_data_filled'] = stats_by_year.notnull().mean(axis=1)

In [602]:
# Identifiez les indicateurs particulièrement riches en données en calculant un dataframe contenant par indicateur et par année, le nombre de pays avec une valeur renseignée.

indicator_with_data_for_country = stats_filtered.groupby(['Indicator Name'])[cols].agg('count')
indicator_with_data_for_country

                                                    2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017
Indicator Name
Adjusted net enrolment rate, lower secondary, b...    95   101   101    94   101   105    98   104   102   112   106   107   101    99    84     3     0     0
Adjusted net enrolment rate, lower secondary, f...    93    95    96    89    97   101    95   101   100   110   103   106   100    98    83     3     0     0
Adjusted net enrolment rate, lower secondary, g...    93    95    96    89    97   101    95   101   100   110   103   106   100    98    83     3     0     0
Adjusted net enrolment rate, lower secondary, m...    93    95    96    89    97   101    95   101   100   110   103   106   100    98    83     3     0     0
Adjusted net enrolment rate, upper secondary, b...    33    25    32    33    39    37    40    42    46    56    57    57    52   100    89     3     0     0
...                                                  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
Youth illiterate population, 15-24 years, % female    43    28    18    10    18    20    26    34    31    32    47    57    41    29    35    31    17     0
Youth literacy rate, population 15-24 years, bo...    43    28    18    10    18    20    26    34    31    32    47    57    41    29    36    32    17     0
Youth literacy rate, population 15-24 years, fe...    43    28    18    10    18    20    26    34    31    32    47    57    41    29    36    32    17     0
Youth literacy rate, population 15-24 years, ge...    43    28    18    10    18    20    26    34    31    32    47    57    41    29    36    32    17     0
Youth literacy rate, population 15-24 years, ma...    43    28    18    10    18    20    26    34    31    32    47    57    41    29    36    32    17     0

[2545 rows x 18 columns]

In [603]:
indicator_with_data_for_country['total_countries'] = indicator_with_data_for_country[cols].sum(axis=1)
indicator_with_data_for_country.sort_values('total_countries', ascending=False)

                                                    2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  total_countries
Indicator Name
Theoretical duration of secondary education (ye...   203   203   203   203   203   203   203   203   203   203   203   202   202   203   203   203   173     0             3419
Theoretical duration of upper secondary educati...   203   203   203   203   203   203   203   203   203   203   203   202   202   203   203   203   173     0             3419
Official entrance age to lower secondary educat...   203   203   203   203   203   203   203   203   203   203   203   202   202   203   203   203   173     0             3419
Population of the official age for upper second...   189   191   192   193   193   193   193   194   194   195   194   195   195   195   196   194   157     0             3253
Population of the official age for lower second...   189   191   192   193   193   193   193   194   194   195   193   195   195   195   195   194   157     0             3251
...                                                  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...              ...
LLECE: Distribution of 4th Grade Mathematics Sc...     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0                0
LLECE: Distribution of 4th Grade Mathematics Sc...     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0                0
LLECE: Distribution of 4th Grade Mathematics Sc...     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0                0
LLECE: Distribution of 4th Grade Mathematics Sc...     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0                0
LLECE: Mean performance on the mathematics scal...     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0     0                0

[2545 rows x 19 columns]

In [604]:
print(f'Nombre de pays : {countries_cleaned.shape[0]}')
print(f'Nombre d\'annee : {len(cols)}')
print(f'Total théorique maxium : {countries_cleaned.shape[0] * len(cols)}')

# On ne garde que les indicateurs qui ont un total de 80% de couverture
indicator_with_data_for_country.loc[indicator_with_data_for_country['total_countries'] > 0.8*(countries_cleaned.shape[0] * len(cols))]

#indicator_with_data_for_country.sort_values('total_countries', ascending=False)

Nombre de pays : 214
Nombre d'annee : 18
Total théorique maxium : 3852

                                                    2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  total_countries
Indicator Name
Official entrance age to lower secondary educat...   203   203   203   203   203   203   203   203   203   203   203   202   202   203   203   203   173     0             3419
Population of the official age for lower second...   189   191   192   193   193   193   193   194   194   195   193   195   195   195   195   194   157     0             3251
Population of the official age for lower second...   189   191   191   192   192   192   192   193   193   194   192   194   194   194   194   193   156     0             3236
Population of the official age for lower second...   189   191   191   192   192   192   192   193   193   194   192   194   194   194   194   193   156     0             3236
Population of the official age for pre-primary ...   190   192   193   193   193   193   193   194   193   194   192   195   193   193   193   192   156     0             3242
Population of the official age for pre-primary ...   190   192   192   192   192   192   192   193   192   193   191   194   192   192   192   191   155     0             3227
Population of the official age for pre-primary ...   190   192   192   192   192   192   192   193   192   193   191   194   192   192   192   191   155     0             3227
Population of the official age for primary educ...   188   190   191   192   192   191   190   192   191   192   188   191   191   191   191   190   154     0             3205
Population of the official age for primary educ...   188   190   190   191   191   190   189   191   190   191   188   190   190   190   190   189   153     0             3191
Population of the official age for primary educ...   188   190   190   191   191   190   189   191   190   191   188   190   190   190   190   189   153     0             3191
Population of the official age for secondary ed...   189   191   192   193   193   193   193   194   194   195   193   194   194   194   195   194   157     0             3248
Population of the official age for secondary ed...   189   191   191   192   192   192   192   193   193   194   192   193   193   193   194   193   156     0             3233
Population of the official age for secondary ed...   189   191   191   192   192   192   192   193   193   194   192   193   193   193   194   193   156     0             3233
Population of the official age for the last gra...   187   189   190   191   191   190   189   191   190   191   187   190   190   190   190   189   153     0             3188
Population of the official age for the last gra...   187   189   189   190   190   189   188   190   189   190   187   189   189   189   189   188   152     0             3174
Population of the official age for the last gra...   187   189   189   190   190   189   188   190   189   190   187   189   189   189   189   188   152     0             3174
Population of the official age for upper second...   189   191   192   193   193   193   193   194   194   195   194   195   195   195   196   194   157     0             3253
Population of the official age for upper second...   189   191   191   192   192   192   192   193   193   194   193   194   194   194   195   193   156     0             3238
Population of the official age for upper second...   189   191   191   192   192   192   192   193   193   194   193   194   194   194   195   193   156     0             3238
Population of the official entrance age to prim...   187   188   188   189   189   188   189   189   188   188   185   188   188   188   186   183   184     0             3185
Population of the official entrance age to prim...   186   187   187   188   188   187   188   188   187   187   184   187   187   187   185   182   183     0             3168
Population of the official entrance age to prim...   186   187   187   188   188   187   188   188   187   187   184   187   187   187   185   182   183     0             3168
Population of the official entrance age to seco...   188   190   190   191   191   191   192   191   191   192   190   193   192   192   190   185   186     0             3235
Population of the official entrance age to seco...   187   189   189   190   190   190   191   190   190   191   189   192   191   191   189   184   185     0             3218
Population of the official entrance age to seco...   187   189   189   190   190   190   191   190   190   191   189   192   191   191   189   184   185     0             3218
Theoretical duration of secondary education (ye...   203   203   203   203   203   203   203   203   203   203   203   202   202   203   203   203   173     0             3419
Theoretical duration of upper secondary educati...   203   203   203   203   203   203   203   203   203   203   203   202   202   203   203   203   173     0             3419