# Analysez les données de systèmes éducatifs

## Exercice partie 1

### Etape 1 - Chargez les données dans votre Notebook

In [1111]:
import pandas as pd

# Permet d'afficher toutes les colonnes du dataframe
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [1112]:
imported_countries = pd.read_csv('data/raw/EdStatsCountry.csv')
imported_country_series = pd.read_csv('data/raw/EdStatsCountry-Series.csv')
imported_data = pd.read_csv('data/raw/EdStatsData.csv')
imported_footnote = pd.read_csv('data/raw/EdStatsFootNote.csv')
imported_series = pd.read_csv('data/raw/EdStatsSeries.csv')

### Etape 2 - Collectez les informations basiques sur chaque jeu de données

In [1113]:
# Fonction d'analyse des jeux de données
def analyze(file_name, data, categorial_columns):

    print(f"Le fichier {file_name} contient {data.shape[0]} lignes pour {data.shape[1]} colonnes. Il y à {data.duplicated().sum()} lignes dupliquée.")
    print("\n")

    for column in data.columns:
        print(column)
        nb_cell_empty = data[column].isnull().sum()
        print(f"Colonne {column} : {nb_cell_empty} cellules vides sur {data.shape[0]}, Soit {round((100 * nb_cell_empty) / data.shape[0])}% cellules vides.")

        # On utilise describe pour les colonnes numériques
        if data[column].dtype == 'int64' or data[column].dtype == 'float64':
            print(data[column].describe())

        # On affiche le nombre d'occurence par groupe pour les colonnes catégorielles
        if column in categorial_columns:
            print(data.groupby(column).size())

        print("\n")

#### **Analyse du fichier EdStatsCountry**

Chaque ligne du fichiers contient des informations sur un pays. Par exemple ci-dessus les informations du pays FRANCE

In [1114]:
# Exemple d'une ligne du jeu de donnée
imported_countries.loc[imported_countries['Country Code'] == 'FRA']

   Country Code Short Name Table Name        Long Name 2-alpha code Currency Unit                                      Special Notes                 Region       Income Group WB-2 code                        National accounts base year  National accounts reference year                SNA price valuation Lending category Other groups                        System of National Accounts Alternative conversion factor PPP survey year             Balance of Payments Manual in use External debt Reporting status       System of trade    Government Accounting concept             IMF data dissemination standard                           Latest population census Latest household survey  Source of most recent Income and expenditure data Vital registration complete Latest agricultural census  Latest industrial data  Latest trade data Latest water withdrawal data  Unnamed: 31
71          FRA     France     France  French Republic           FR          Euro  A simple multiplier is used to convert the nat...  Europe & Central Asia  High income: OECD        FR  Original chained constant price data are resca...                              2005  Value added at basic prices (VAB)              NaN    Euro area  Country uses the 1993 System of National Accou...                           NaN         Rolling  IMF Balance of Payments Manual, 6th edition.                            NaN  Special trade system  Consolidated central government  Special Data Dissemination Standard (SDDS)  2006. Rolling census based on continuous sampl...                     NaN  Expenditure survey/budget survey (ES/BS), 1994/95                         Yes                       2010                    2009               2012                         2007          NaN

In [1115]:
categorial_cols = ['Region', 'Income Group', 'National accounts base year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'PPP survey year', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census']

# Analyse du fichier
analyze('EdStatsCountry', imported_countries, categorial_cols)

Le fichier EdStatsCountry contient 241 lignes pour 31 colonnes. Il y à 0 lignes dupliquée.


Country Code
Colonne Country Code : 0 cellules vides sur 241, Soit 0% cellules vides.


Short Name
Colonne Short Name : 0 cellules vides sur 241, Soit 0% cellules vides.


Table Name
Colonne Table Name : 0 cellules vides sur 241, Soit 0% cellules vides.


Long Name
Colonne Long Name : 0 cellules vides sur 241, Soit 0% cellules vides.


2-alpha code
Colonne 2-alpha code : 3 cellules vides sur 241, Soit 1% cellules vides.


Currency Unit
Colonne Currency Unit : 26 cellules vides sur 241, Soit 11% cellules vides.


Special Notes
Colonne Special Notes : 96 cellules vides sur 241, Soit 40% cellules vides.


Region
Colonne Region : 27 cellules vides sur 241, Soit 11% cellules vides.
Region
East Asia & Pacific           36
Europe & Central Asia         57
Latin America & Caribbean     41
Middle East & North Africa    21
North America                  3
South Asia                     8
Sub-Saharan Africa            48
dtype: int64


Income Group
Colonne Income Group : 27 cellules vides sur 241, Soit 11% cellules vides.
Income Group
High income: OECD       31
High income: nonOECD    44
Low income              34
Lower middle income     50
Upper middle income     55
dtype: int64


WB-2 code
Colonne WB-2 code : 1 cellules vides sur 241, Soit 0% cellules vides.


National accounts base year
Colonne National accounts base year : 36 cellules vides sur 241, Soit 15% cellules vides.
National accounts base year
1954                                                                                                                        1
1974                                                                                                                        1
1980                                                                                                                        1
1981/82. Reporting period switch from fiscal year to calendar year from 1996. Pre-1996 data converted to calendar year.     1
1982                                                                                                                        1
1984                                                                                                                        1
1985                                                                                                                        3
1986/87                                                                                                                     1
1987                                                                                                                        1
1988                                                                                                                        3
1990                                                                                                                       11
1990/91                                                                                                                     1
1991                                                                                                                        3
1991/92                                                                                                                     1
1994                                                                                                                        3
1995                                                                                                                        2
1995/96                                                                                                                     1
1996                                                                                                                        1
1997                                                                                                                        2
1997/98                                                                                                                     1
1998                                                                                                                        3
1999                                                                                                                        4
2000                                                                                                                       25
2000/01                                                                                                                     1
2001                                                                                                                        3
2001/02                                                                                                                     1
2002                                                                                                                        4
2002/03                                                                                                                     1
2003                                                                                                                        5
2004                                                                                                                        8
2004/05                                                                                                                     1
2005                                                                                                                       34
2005/06                                                                                                                     2
2005/2006                                                                                                                   1
2006                                                                                                                       19
2007                                                                                                                        9
2008                                                                                                                        3
2009                                                                                                                        3
2010                                                                                                                        6
2010/11                                                                                                                     1
2011                                                                                                                        2
2012                                                                                                                        1
Original chained constant price data are rescaled.                                                                         28
dtype: int64


National accounts reference year
Colonne National accounts reference year : 209 cellules vides sur 241, Soit 87% cellules vides.
count     32
mean    2002
std        5
min     1987
25%     1997
50%     2002
75%     2005
max     2012
Name: National accounts reference year, dtype: float64


SNA price valuation
Colonne SNA price valuation : 44 cellules vides sur 241, Soit 18% cellules vides.
SNA price valuation
Value added at basic prices (VAB)       163
Value added at producer prices (VAP)     34
dtype: int64


Lending category
Colonne Lending category : 97 cellules vides sur 241, Soit 40% cellules vides.
Lending category
Blend    18
IBRD     67
IDA      59
dtype: int64


Other groups
Colonne Other groups : 183 cellules vides sur 241, Soit 76% cellules vides.
Other groups
Euro area    18
HIPC         40
dtype: int64


System of National Accounts
Colonne System of National Accounts : 26 cellules vides sur 241, Soit 11% cellules vides.
System of National Accounts
Country uses the 1968 System of National Accounts methodology.     42
Country uses the 1993 System of National Accounts methodology.    165
Country uses the 2008 System of National Accounts methodology.      8
dtype: int64


Alternative conversion factor
Colonne Alternative conversion factor : 194 cellules vides sur 241, Soit 80% cellules vides.


PPP survey year
Colonne PPP survey year : 96 cellules vides sur 241, Soit 40% cellules vides.
PPP survey year
2005       98
2011       10
Rolling    37
dtype: int64


Balance of Payments Manual in use
Colonne Balance of Payments Manual in use : 60 cellules vides sur 241, Soit 25% cellules vides.


External debt Reporting status
Colonne External debt Reporting status : 117 cellules vides sur 241, Soit 49% cellules vides.
External debt Reporting status
Actual         107
Estimate        11
Preliminary      6
dtype: int64


System of trade
Colonne System of trade : 41 cellules vides sur 241, Soit 17% cellules vides.
System of trade
General trade system    106
Special trade system     94
dtype: int64


Government Accounting concept
Colonne Government Accounting concept : 80 cellules vides sur 241, Soit 33% cellules vides.
Government Accounting concept
Budgetary central government       66
Consolidated central government    95
dtype: int64


IMF data dissemination standard
Colonne IMF data dissemination standard : 60 cellules vides sur 241, Soit 25% cellules vides.
IMF data dissemination standard
General Data Dissemination System (GDDS)      110
Special Data Dissemination Standard (SDDS)     71
dtype: int64


Latest population census
Colonne Latest population census : 28 cellules vides sur 241, Soit 12% cellules vides.
Latest population census
1970                                                                                                                                                                               2
1979                                                                                                                                                                               1
1983                                                                                                                                                                               1
1984                                                                                                                                                                               2
1987                                                                                                                                                                               1
1989                                                                                                                                                                               1
1993                                                                                                                                                                               1
1996                                                                                                                                                                               1
1997                                                                                                                                                                               1
1998                                                                                                                                                                               2
2001                                                                                                                                                                               1
2002                                                                                                                                                                               5
2003                                                                                                                                                                               3
2004                                                                                                                                                                               7
2005                                                                                                                                                                               4
2006                                                                                                                                                                               8
2006. Rolling census based on continuous sample survey.                                                                                                                            1
2007                                                                                                                                                                               9
2008                                                                                                                                                                               9
2009                                                                                                                                                                              14
2010                                                                                                                                                                              49
2011                                                                                                                                                                              59
2011. Population figures compiled from administrative registers.                                                                                                                   3
2011. The population censuses for 1986 and 1996 were based on a one-in-seven sample of the population, while that for 2006 was based on a one-in-ten sample of the population.     1
2012                                                                                                                                                                              18
2013                                                                                                                                                                               8
Guernsey: 2009; Jersey: 2011.                                                                                                                                                      1
dtype: int64


Latest household survey
Colonne Latest household survey : 100 cellules vides sur 241, Soit 41% cellules vides.


Source of most recent Income and expenditure data
Colonne Source of most recent Income and expenditure data : 81 cellules vides sur 241, Soit 34% cellules vides.


Vital registration complete
Colonne Vital registration complete : 130 cellules vides sur 241, Soit 54% cellules vides.


Latest agricultural census
Colonne Latest agricultural census : 99 cellules vides sur 241, Soit 41% cellules vides.


Latest industrial data
Colonne Latest industrial data : 134 cellules vides sur 241, Soit 56% cellules vides.
count    107
mean    2008
std        3
min     2000
25%     2008
50%     2009
75%     2010
max     2010
Name: Latest industrial data, dtype: float64


Latest trade data
Colonne Latest trade data : 56 cellules vides sur 241, Soit 23% cellules vides.
count    185
mean    2011
std        3
min     1995
25%     2011
50%     2012
75%     2012
max     2012
Name: Latest trade data, dtype: float64


Latest water withdrawal data
Colonne Latest water withdrawal data : 62 cellules vides sur 241, Soit 26% cellules vides.

#### **Analyse du fichier EdStatsCountry-Series**

Chaque ligne du fichier contient des informations complémentaires sur les données.

C'est aussi une table de correspondance entre le fichier Pays et le fichier Stats

La clé CountryCode correspond a la clé Country Code dans le fichier EdStatsCountry, et la clé SeriesCode correspond à la clé Indicator Code dans le fichier EdStatsData

In [1116]:
imported_country_series.loc[imported_country_series['CountryCode'] == 'FRA']

    CountryCode         SeriesCode                                        DESCRIPTION  Unnamed: 3
166         FRA        SP.POP.GROW  Data sources: Eurostat, United Nations World P...         NaN
167         FRA  SP.POP.TOTL.MA.ZS  Including the four French overseas departments...         NaN
168         FRA  SP.POP.TOTL.FE.ZS  Including the four French overseas departments...         NaN
169         FRA        SP.POP.TOTL  Data sources : Eurostat, United Nations World ...         NaN
170         FRA  SP.POP.0014.TO.ZS  Including the four French overseas departments...         NaN
171         FRA  SP.POP.1564.TO.ZS  Including the four French overseas departments...         NaN

In [1117]:
analyze('EdStatsCountrySeries', imported_country_series, [])

Le fichier EdStatsCountrySeries contient 613 lignes pour 3 colonnes. Il y à 0 lignes dupliquée.


CountryCode
Colonne CountryCode : 0 cellules vides sur 613, Soit 0% cellules vides.


SeriesCode
Colonne SeriesCode : 0 cellules vides sur 613, Soit 0% cellules vides.


DESCRIPTION
Colonne DESCRIPTION : 0 cellules vides sur 613, Soit 0% cellules vides.

#### **Anayse du fichier EdStatsData**

Chaque ligne du fichier contient des statistiques par année

In [1118]:
imported_data.head(2)

  Country Name Country Code                                     Indicator Name Indicator Code  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2020  2025  2030  2035  2040  2045  2050  2055  2060  2065  2070  2075  2080  2085  2090  2095  2100  Unnamed: 69
0   Arab World          ARB  Adjusted net enrolment rate, lower secondary, ...     UIS.NERA.2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN
1   Arab World          ARB  Adjusted net enrolment rate, lower secondary, ...   UIS.NERA.2.F   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN

In [1119]:
analyze('EdStatsData', imported_data, [])

Le fichier EdStatsData contient 886930 lignes pour 69 colonnes. Il y à 0 lignes dupliquée.


Country Name
Colonne Country Name : 0 cellules vides sur 886930, Soit 0% cellules vides.


Country Code
Colonne Country Code : 0 cellules vides sur 886930, Soit 0% cellules vides.


Indicator Name
Colonne Indicator Name : 0 cellules vides sur 886930, Soit 0% cellules vides.


Indicator Code
Colonne Indicator Code : 0 cellules vides sur 886930, Soit 0% cellules vides.


1970
Colonne 1970 : 814642 cellules vides sur 886930, Soit 92% cellules vides.
count            72288
mean        1974772450
std       121168685352
min                 -1
25%                  1
50%                  6
75%                 63
max     19039286948196
Name: 1970, dtype: float64


1971
Colonne 1971 : 851393 cellules vides sur 886930, Soit 96% cellules vides.
count            35537
mean        4253638470
std       180481446225
min                 -2
25%                  9
50%                 63
75%              56552
max     19864566419298
Name: 1971, dtype: float64


1972
Colonne 1972 : 851311 cellules vides sur 886930, Soit 96% cellules vides.
count            35619
mean        4592364905
std       191408271480
min                 -3
25%                  9
50%                 67
75%              58636
max     21009161433401
Name: 1972, dtype: float64


1973
Colonne 1973 : 851385 cellules vides sur 886930, Soit 96% cellules vides.
count            35545
mean        5105005611
std       205917043981
min                 -4
25%                 10
50%                 70
75%              62029
max     22383671023495
Name: 1973, dtype: float64


1974
Colonne 1974 : 851200 cellules vides sur 886930, Soit 96% cellules vides.
count            35730
mean        5401492903
std       211214985371
min                 -4
25%                 10
50%                 71
75%              63837
max     22829911729819
Name: 1974, dtype: float64


1975
Colonne 1975 : 799624 cellules vides sur 886930, Soit 90% cellules vides.
count            87306
mean        2314287512
std       137505922745
min                 -4
25%                  1
50%                 10
75%                 79
max     23006343161670
Name: 1975, dtype: float64


1976
Colonne 1976 : 849447 cellules vides sur 886930, Soit 96% cellules vides.
count            37483
mean        5731808142
std       221554619977
min                 -3
25%                  9
50%                 71
75%              56828
max     24241276811573
Name: 1976, dtype: float64


1977
Colonne 1977 : 849356 cellules vides sur 886930, Soit 96% cellules vides.
count            37574
mean        6124437154
std       232548901067
min                 -3
25%                 10
50%                 71
75%              57392
max     25213826643314
Name: 1977, dtype: float64


1978
Colonne 1978 : 849354 cellules vides sur 886930, Soit 96% cellules vides.
count            37576
mean        6671488719
std       247398632281
min                 -4
25%                 10
50%                 73
75%              59404
max     26221014860338
Name: 1978, dtype: float64


1979
Colonne 1979 : 850121 cellules vides sur 886930, Soit 96% cellules vides.
count            36809
mean        7436723955
std       266095745106
min                 -3
25%                 10
50%                 75
75%              64115
max     27308727186243
Name: 1979, dtype: float64


1980
Colonne 1980 : 797808 cellules vides sur 886930, Soit 90% cellules vides.
count            89122
mean        3283897509
std       178077355006
min                 -1
25%                  2
50%                 11
75%                 82
max     27843189307932
Name: 1980, dtype: float64


1981
Colonne 1981 : 848153 cellules vides sur 886930, Soit 96% cellules vides.
count            38777
mean        7664969392
std       274414168519
min                 -1
25%                  9
50%                 75
75%              63104
max     28379257951893
Name: 1981, dtype: float64


1982
Colonne 1982 : 849419 cellules vides sur 886930, Soit 96% cellules vides.
count            37511
mean        7913721582
std       279054890539
min                 -2
25%                 10
50%                 77
75%              69233
max     28480670615135
Name: 1982, dtype: float64


1983
Colonne 1983 : 848470 cellules vides sur 886930, Soit 96% cellules vides.
count            38460
mean        7856908292
std       282380912099
min                 -3
25%                 10
50%                 76
75%              63041
max     29164360664954
Name: 1983, dtype: float64


1984
Colonne 1984 : 848324 cellules vides sur 886930, Soit 96% cellules vides.
count            38606
mean        8118001691
std       294063483007
min                 -3
25%                  9
50%                 75
75%              63607
max     30485211655932
Name: 1984, dtype: float64


1985
Colonne 1985 : 796634 cellules vides sur 886930, Soit 90% cellules vides.
count            90296
mean        3622763070
std       200292918507
min                 -2
25%                  2
50%                 12
75%                 83
max     31664646793714
Name: 1985, dtype: float64


1986
Colonne 1986 : 847558 cellules vides sur 886930, Soit 96% cellules vides.
count            39372
mean        9156550108
std       326467474654
min                 -2
25%                  9
50%                 74
75%              66085
max     32712843955205
Name: 1986, dtype: float64


1987
Colonne 1987 : 848289 cellules vides sur 886930, Soit 96% cellules vides.
count            38641
mean       10149008176
std       353535110136
min                 -1
25%                 10
50%                 74
75%              70011
max     33882440955342
Name: 1987, dtype: float64


1988
Colonne 1988 : 848378 cellules vides sur 886930, Soit 96% cellules vides.
count            38552
mean       11047093701
std       380425690033
min                 -1
25%                 10
50%                 74
75%              75979
max     35457378555163
Name: 1988, dtype: float64


1989
Colonne 1989 : 849390 cellules vides sur 886930, Soit 96% cellules vides.
count            37540
mean       11954359465
std       401487301933
min                 -2
25%                 10
50%                 79
75%              85584
max     36787413390636
Name: 1989, dtype: float64


1990
Colonne 1990 : 762525 cellules vides sur 886930, Soit 86% cellules vides.
count           124405
mean        9084423551
std       366566685062
min                 -2
25%                  5
50%                 50
75%              91343
max     47143438466903
Name: 1990, dtype: float64


1991
Colonne 1991 : 812493 cellules vides sur 886930, Soit 92% cellules vides.
count            74437
mean       15716740024
std       488135688946
min                 -6
25%                 51
50%              39160
75%             438313
max     47812717689115
Name: 1991, dtype: float64


1992
Colonne 1992 : 811387 cellules vides sur 886930, Soit 91% cellules vides.
count            75543
mean       16046684981
std       501205532250
min                 -5
25%                 49
50%              34773
75%             424612
max     48664457634800
Name: 1992, dtype: float64


1993
Colonne 1993 : 811137 cellules vides sur 886930, Soit 91% cellules vides.
count            75793
mean       16435324912
std       512196248891
min                 -6
25%                 49
50%              34971
75%             431625
max     49596000966259
Name: 1993, dtype: float64


1994
Colonne 1994 : 809468 cellules vides sur 886930, Soit 91% cellules vides.
count            77462
mean       16840220344
std       529298242836
min                 -5
25%                 48
50%              31825
75%             424460
max     51065807538866
Name: 1994, dtype: float64


1995
Colonne 1995 : 755569 cellules vides sur 886930, Soit 85% cellules vides.
count           131361
mean       10525426793
std       428521845884
min                 -3
25%                  5
50%                 50
75%              79540
max     52754475204801
Name: 1995, dtype: float64


1996
Colonne 1996 : 810123 cellules vides sur 886930, Soit 91% cellules vides.
count            76807
mean       18746300978
std       581258593846
min                 -4
25%                 48
50%              32624
75%             437106
max     54780314314472
Name: 1996, dtype: float64


1997
Colonne 1997 : 813477 cellules vides sur 886930, Soit 92% cellules vides.
count            73453
mean       20273850045
std       614235660875
min                 -3
25%                 55
50%              43196
75%             490970
max     56955214645836
Name: 1997, dtype: float64


1998
Colonne 1998 : 802016 cellules vides sur 886930, Soit 90% cellules vides.
count            84914
mean       17946782924
std       585914770746
min             -60862
25%                 33
50%              15214
75%             376821
max     58351373560297
Name: 1998, dtype: float64


1999
Colonne 1999 : 768091 cellules vides sur 886930, Soit 87% cellules vides.
count           118839
mean       13315578554
std       515347248865
min             -65260
25%                 17
50%               1251
75%             186736
max     60406324400195
Name: 1999, dtype: float64


2000
Colonne 2000 : 710254 cellules vides sur 886930, Soit 80% cellules vides.
count           176676
mean        9423383684
std       444237415250
min             -67593
25%                  6
50%                 51
75%              33440
max     63272930868730
Name: 2000, dtype: float64


2001
Colonne 2001 : 763421 cellules vides sur 886930, Soit 86% cellules vides.
count           123509
mean       13848674154
std       544924199158
min             -69737
25%                 16
50%                830
75%             174654
max     64778339442512
Name: 2001, dtype: float64


2002
Colonne 2002 : 762725 cellules vides sur 886930, Soit 86% cellules vides.
count           124205
mean       14282985240
std       562288604615
min             -92143
25%                 16
50%                946
75%             177099
max     66547530649453
Name: 2002, dtype: float64


2003
Colonne 2003 : 756567 cellules vides sur 886930, Soit 85% cellules vides.
count           130363
mean       14493931504
std       580360721927
min            -111186
25%                 16
50%                396
75%             147479
max     69063279399840
Name: 2003, dtype: float64


2004
Colonne 2004 : 758116 cellules vides sur 886930, Soit 85% cellules vides.
count           128814
mean       15897290511
std       627833708489
min            -126260
25%                 14
50%                335
75%             158408
max     72788290554396
Name: 2004, dtype: float64


2005
Colonne 2005 : 702822 cellules vides sur 886930, Soit 79% cellules vides.
count           184108
mean       11886369143
std       557618094904
min            -134724
25%                  6
50%                 50
75%              29932
max     76240446997339
Name: 2005, dtype: float64


2006
Colonne 2006 : 746618 cellules vides sur 886930, Soit 84% cellules vides.
count           140312
mean       16846738102
std       685148411394
min            -370894
25%                 13
50%                100
75%             118720
max     80318399991191
Name: 2006, dtype: float64


2007
Colonne 2007 : 749658 cellules vides sur 886930, Soit 85% cellules vides.
count           137272
mean       18723002079
std       746568758042
min            -388217
25%                 13
50%                100
75%             134379
max     84691447699464
Name: 2007, dtype: float64


2008
Colonne 2008 : 752543 cellules vides sur 886930, Soit 85% cellules vides.
count           134387
mean       20297938642
std       794413214847
min            -408854
25%                 12
50%                100
75%             145386
max     87110219802679
Name: 2008, dtype: float64


2009
Colonne 2009 : 744822 cellules vides sur 886930, Soit 84% cellules vides.
count           142108
mean       18949069733
std       762364956966
min            -456124
25%                 12
50%                 99
75%             118041
max     86775163961908
Name: 2009, dtype: float64


2010
Colonne 2010 : 644488 cellules vides sur 886930, Soit 73% cellules vides.
count           242442
mean       11895924325
std       621870964577
min            -496905
25%                  1
50%                 20
75%               3121
max     91346761245407
Name: 2010, dtype: float64


2011
Colonne 2011 : 740918 cellules vides sur 886930, Soit 84% cellules vides.
count           146012
mean       21179108774
std       855585335680
min            -570994
25%                 12
50%                 99
75%             106506
max     95063136211954
Name: 2011, dtype: float64


2012
Colonne 2012 : 739666 cellules vides sur 886930, Soit 83% cellules vides.
count           147264
mean       21763227128
std       883395495201
min            -604993
25%                 11
50%                 98
75%             103817
max     99994730175215
Name: 2012, dtype: float64


2013
Colonne 2013 : 749421 cellules vides sur 886930, Soit 84% cellules vides.
count            137509
mean        24253320032
std        951301602368
min             -615748
25%                  13
50%                 100
75%              142648
max     105457955976107
Name: 2013, dtype: float64


2014
Colonne 2014 : 773141 cellules vides sur 886930, Soit 87% cellules vides.
count            113789
mean        26784486485
std       1023180279185
min                 -89
25%                  16
50%                 100
75%              163644
max     110805995944461
Name: 2014, dtype: float64


2015
Colonne 2015 : 755872 cellules vides sur 886930, Soit 85% cellules vides.
count            131058
mean        23537199876
std        973246472636
min                  -2
25%                   0
50%                  52
75%               61536
max     115619758353829
Name: 2015, dtype: float64


2016
Colonne 2016 : 870470 cellules vides sur 886930, Soit 98% cellules vides.
count             16460
mean       193441064053
std       2839188497132
min                  -2
25%                  18
50%                6264
75%              593959
max     120603020118353
Name: 2016, dtype: float64


2017
Colonne 2017 : 886787 cellules vides sur 886930, Soit 100% cellules vides.
count   143
mean      2
std       1
min       1
25%       2
50%       2
75%       3
max       4
Name: 2017, dtype: float64


2020
Colonne 2020 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        578
std       14751
min          -2
25%           0
50%           0
75%           7
max     1599479
Name: 2020, dtype: float64


2025
Colonne 2025 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        605
std       15773
min          -2
25%           0
50%           0
75%           7
max     1781898
Name: 2025, dtype: float64


2030
Colonne 2030 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        632
std       16786
min          -2
25%           0
50%           0
75%           7
max     1967258
Name: 2030, dtype: float64


2035
Colonne 2035 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        656
std       17787
min          -2
25%           0
50%           0
75%           7
max     2151416
Name: 2035, dtype: float64


2040
Colonne 2040 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        675
std       18744
min          -2
25%           0
50%           0
75%           7
max     2330336
Name: 2040, dtype: float64


2045
Colonne 2045 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        691
std       19654
min          -2
25%           0
50%           0
75%           7
max     2500439
Name: 2045, dtype: float64


2050
Colonne 2050 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        704
std       20529
min          -2
25%           0
50%           0
75%           8
max     2662071
Name: 2050, dtype: float64


2055
Colonne 2055 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        715
std       21369
min          -2
25%           0
50%           0
75%           8
max     2813670
Name: 2055, dtype: float64


2060
Colonne 2060 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        722
std       22158
min          -2
25%           0
50%           0
75%           8
max     2951569
Name: 2060, dtype: float64


2065
Colonne 2065 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        727
std       22880
min          -1
25%           0
50%           0
75%           8
max     3070879
Name: 2065, dtype: float64


2070
Colonne 2070 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        728
std       23523
min          -1
25%           0
50%           0
75%           7
max     3169711
Name: 2070, dtype: float64


2075
Colonne 2075 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        727
std       24081
min          -1
25%           0
50%           0
75%           7
max     3246239
Name: 2075, dtype: float64


2080
Colonne 2080 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        723
std       24559
min          -1
25%           0
50%           0
75%           7
max     3301586
Name: 2080, dtype: float64


2085
Colonne 2085 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        718
std       24966
min          -1
25%           0
50%           0
75%           6
max     3337871
Name: 2085, dtype: float64


2090
Colonne 2090 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        711
std       25302
min          -1
25%           0
50%           0
75%           5
max     3354746
Name: 2090, dtype: float64


2095
Colonne 2095 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        703
std       25561
min          -1
25%           0
50%           0
75%           5
max     3351887
Name: 2095, dtype: float64


2100
Colonne 2100 : 835494 cellules vides sur 886930, Soit 94% cellules vides.
count     51436
mean        694
std       25742
min          -0
25%           0
50%           0
75%           4
max     3330484
Name: 2100, dtype: float64

In [1120]:
imported_data.head(2)

  Country Name CountryCode                                     Indicator Name    SeriesCode  1970  1971  1972  1973  1974  1975  1976  1977  1978  1979  1980  1981  1982  1983  1984  1985  1986  1987  1988  1989  1990  1991  1992  1993  1994  1995  1996  1997  1998  1999  2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  2014  2015  2016  2017  2020  2025  2030  2035  2040  2045  2050  2055  2060  2065  2070  2075  2080  2085  2090  2095  2100
0   Arab World         ARB  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1   Arab World         ARB  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.F   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

#### **Analyse du fichier EdStatsFootNote**

Chaque ligne du fichier contient du détail pour certaines lignes de EdStatsData

La clé SeriesCode correspond à la clé Indicator Code dans le fichier EdStatsData

In [1121]:
imported_footnote.head(2)

  CountryCode      SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.         NaN

In [1122]:
analyze('EdStatsFootNote', imported_footnote, [])

Le fichier EdStatsFootNote contient 643638 lignes pour 4 colonnes. Il y à 0 lignes dupliquée.


CountryCode
Colonne CountryCode : 0 cellules vides sur 643638, Soit 0% cellules vides.


SeriesCode
Colonne SeriesCode : 0 cellules vides sur 643638, Soit 0% cellules vides.


Year
Colonne Year : 0 cellules vides sur 643638, Soit 0% cellules vides.


DESCRIPTION
Colonne DESCRIPTION : 0 cellules vides sur 643638, Soit 0% cellules vides.

#### **Analyse du fichier EdStatsSeries**

Chaque ligne du fichier contient des explication concernant le type de donnée enregistré dans chaque cellule par année.

La clé Series Code correspond à la clé Indicator Code dans le fichier EdStatsData

In [1123]:
imported_series.head(2)

           Series Code       Topic                                     Indicator Name                                   Short definition                                    Long definition  Unit of measure Periodicity Base Period Other notes Aggregation method Limitations and exceptions  Notes from original source General comments                                             Source Statistical concept and methodology Development relevance Related source links  Other web links  Related indicators  License Type  Unnamed: 20
0  BAR.NOED.1519.FE.ZS  Attainment  Barro-Lee: Percentage of female population age...  Percentage of female population age 15-19 with...  Percentage of female population age 15-19 with...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN          NaN
1     BAR.NOED.1519.ZS  Attainment  Barro-Lee: Percentage of population age 15-19 ...  Percentage of population age 15-19 with no edu...  Percentage of population age 15-19 with no edu...              NaN         NaN         NaN         NaN                NaN                        NaN                         NaN              NaN  Robert J. Barro and Jong-Wha Lee: http://www.b...                                 NaN                   NaN                  NaN              NaN                 NaN           NaN          NaN

In [1124]:
analyze('EdStatsSeries', imported_series, [])

Le fichier EdStatsSeries contient 3665 lignes pour 20 colonnes. Il y à 0 lignes dupliquée.


Series Code
Colonne Series Code : 0 cellules vides sur 3665, Soit 0% cellules vides.


Topic
Colonne Topic : 0 cellules vides sur 3665, Soit 0% cellules vides.


Indicator Name
Colonne Indicator Name : 0 cellules vides sur 3665, Soit 0% cellules vides.


Short definition
Colonne Short definition : 1509 cellules vides sur 3665, Soit 41% cellules vides.


Long definition
Colonne Long definition : 0 cellules vides sur 3665, Soit 0% cellules vides.


Unit of measure
Colonne Unit of measure : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count     0
mean    NaN
std     NaN
min     NaN
25%     NaN
50%     NaN
75%     NaN
max     NaN
Name: Unit of measure, dtype: float64


Periodicity
Colonne Periodicity : 3566 cellules vides sur 3665, Soit 97% cellules vides.


Base Period
Colonne Base Period : 3351 cellules vides sur 3665, Soit 91% cellules vides.


Other notes
Colonne Other notes : 3113 cellules vides sur 3665, Soit 85% cellules vides.


Aggregation method
Colonne Aggregation method : 3618 cellules vides sur 3665, Soit 99% cellules vides.


Limitations and exceptions
Colonne Limitations and exceptions : 3651 cellules vides sur 3665, Soit 100% cellules vides.


Notes from original source
Colonne Notes from original source : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count     0
mean    NaN
std     NaN
min     NaN
25%     NaN
50%     NaN
75%     NaN
max     NaN
Name: Notes from original source, dtype: float64


General comments
Colonne General comments : 3651 cellules vides sur 3665, Soit 100% cellules vides.


Source
Colonne Source : 0 cellules vides sur 3665, Soit 0% cellules vides.


Statistical concept and methodology
Colonne Statistical concept and methodology : 3642 cellules vides sur 3665, Soit 99% cellules vides.


Development relevance
Colonne Development relevance : 3662 cellules vides sur 3665, Soit 100% cellules vides.


Related source links
Colonne Related source links : 3450 cellules vides sur 3665, Soit 94% cellules vides.


Other web links
Colonne Other web links : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count     0
mean    NaN
std     NaN
min     NaN
25%     NaN
50%     NaN
75%     NaN
max     NaN
Name: Other web links, dtype: float64


Related indicators
Colonne Related indicators : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count     0
mean    NaN
std     NaN
min     NaN
25%     NaN
50%     NaN
75%     NaN
max     NaN
Name: Related indicators, dtype: float64


License Type
Colonne License Type : 3665 cellules vides sur 3665, Soit 100% cellules vides.
count     0
mean    NaN
std     NaN
min     NaN
25%     NaN
50%     NaN
75%     NaN
max     NaN
Name: License Type, dtype: float64